# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install deps
      run: sudo apt-get install libsdl2-dev

    - name: Install Tundra
      run: git clone --recursive https://github.com/deplinenoise/tundra.git && cd tundra && make -j2 && sudo make install && cd ..

    - name: Build Debug
      run: |
        tundra2 linux-gcc-release

# Build macOS
  build_macOS:
    runs-on: macOS-latest
    steps:
    - name: Build Release
      run: |
        export QT5_BIN=$Qt5_DIR/bin
        export QT5_INC=$Qt5_DIR/include
        export QT5_LIB=$Qt5_DIR/lib
        bin/macos/tundra2 macosx-clang-release

# Build Windows
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Build Release 
      shell: cmd
      run: |
        bin\win32\tundra2.exe --unprotected win32-msvc-release
